steps:
  # Build base image
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/base", "-f", "Dockerfile.base", "."]

  # Build and push host app
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/host",
        "-f",
        "apps/host/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/host"]

  # Build and push tickets app
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/tickets",
        "-f",
        "apps/tickets/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/tickets"]

  # Build and push admin-settings app
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/admin-settings",
        "-f",
        "apps/admin-settings/Dockerfile",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/admin-settings"]

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "host"
      - "--image"
      - "gcr.io/$PROJECT_ID/host"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "tickets"
      - "--image"
      - "gcr.io/$PROJECT_ID/tickets"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "admin-settings"
      - "--image"
      - "gcr.io/$PROJECT_ID/admin-settings"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

images:
  - "gcr.io/$PROJECT_ID/host"
  - "gcr.io/$PROJECT_ID/tickets"
  - "gcr.io/$PROJECT_ID/admin-settings"

timeout: "3600s"
